/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Exchange {
  export type MarketConfigStruct = {
    active: boolean;
    baseToken: AddressLike;
    quoteToken: AddressLike;
    minOrderSize: BigNumberish;
    tickSize: BigNumberish;
  };

  export type MarketConfigStructOutput = [
    active: boolean,
    baseToken: string,
    quoteToken: string,
    minOrderSize: bigint,
    tickSize: bigint
  ] & {
    active: boolean;
    baseToken: string;
    quoteToken: string;
    minOrderSize: bigint;
    tickSize: bigint;
  };
}

export interface ExchangeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMarket"
      | "getMarket"
      | "isMarketActive"
      | "markets"
      | "owner"
      | "renounceOwnership"
      | "setMarketStatus"
      | "setSettlementOperator"
      | "settlement"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketAdded"
      | "MarketStatusUpdated"
      | "OwnershipTransferred"
      | "SettlementUpdated"
      | "VaultUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMarket",
    values: [string, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getMarket", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isMarketActive",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketStatus",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMarketActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settlement", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace MarketAddedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    baseToken: AddressLike,
    quoteToken: AddressLike
  ];
  export type OutputTuple = [
    marketId: string,
    baseToken: string,
    quoteToken: string
  ];
  export interface OutputObject {
    marketId: string;
    baseToken: string;
    quoteToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketStatusUpdatedEvent {
  export type InputTuple = [marketId: BytesLike, active: boolean];
  export type OutputTuple = [marketId: string, active: boolean];
  export interface OutputObject {
    marketId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementUpdatedEvent {
  export type InputTuple = [
    oldSettlement: AddressLike,
    newSettlement: AddressLike
  ];
  export type OutputTuple = [oldSettlement: string, newSettlement: string];
  export interface OutputObject {
    oldSettlement: string;
    newSettlement: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUpdatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Exchange extends BaseContract {
  connect(runner?: ContractRunner | null): Exchange;
  waitForDeployment(): Promise<this>;

  interface: ExchangeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMarket: TypedContractMethod<
    [
      marketId: string,
      baseToken: AddressLike,
      quoteToken: AddressLike,
      minOrderSize: BigNumberish,
      tickSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getMarket: TypedContractMethod<
    [marketId: string],
    [Exchange.MarketConfigStructOutput],
    "view"
  >;

  isMarketActive: TypedContractMethod<[marketId: string], [boolean], "view">;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, string, string, bigint, bigint] & {
        active: boolean;
        baseToken: string;
        quoteToken: string;
        minOrderSize: bigint;
        tickSize: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMarketStatus: TypedContractMethod<
    [marketId: string, active: boolean],
    [void],
    "nonpayable"
  >;

  setSettlementOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  settlement: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMarket"
  ): TypedContractMethod<
    [
      marketId: string,
      baseToken: AddressLike,
      quoteToken: AddressLike,
      minOrderSize: BigNumberish,
      tickSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: string],
    [Exchange.MarketConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMarketActive"
  ): TypedContractMethod<[marketId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, string, string, bigint, bigint] & {
        active: boolean;
        baseToken: string;
        quoteToken: string;
        minOrderSize: bigint;
        tickSize: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketStatus"
  ): TypedContractMethod<
    [marketId: string, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlementOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlement"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MarketAdded"
  ): TypedContractEvent<
    MarketAddedEvent.InputTuple,
    MarketAddedEvent.OutputTuple,
    MarketAddedEvent.OutputObject
  >;
  getEvent(
    key: "MarketStatusUpdated"
  ): TypedContractEvent<
    MarketStatusUpdatedEvent.InputTuple,
    MarketStatusUpdatedEvent.OutputTuple,
    MarketStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlementUpdated"
  ): TypedContractEvent<
    SettlementUpdatedEvent.InputTuple,
    SettlementUpdatedEvent.OutputTuple,
    SettlementUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUpdated"
  ): TypedContractEvent<
    VaultUpdatedEvent.InputTuple,
    VaultUpdatedEvent.OutputTuple,
    VaultUpdatedEvent.OutputObject
  >;

  filters: {
    "MarketAdded(bytes32,address,address)": TypedContractEvent<
      MarketAddedEvent.InputTuple,
      MarketAddedEvent.OutputTuple,
      MarketAddedEvent.OutputObject
    >;
    MarketAdded: TypedContractEvent<
      MarketAddedEvent.InputTuple,
      MarketAddedEvent.OutputTuple,
      MarketAddedEvent.OutputObject
    >;

    "MarketStatusUpdated(bytes32,bool)": TypedContractEvent<
      MarketStatusUpdatedEvent.InputTuple,
      MarketStatusUpdatedEvent.OutputTuple,
      MarketStatusUpdatedEvent.OutputObject
    >;
    MarketStatusUpdated: TypedContractEvent<
      MarketStatusUpdatedEvent.InputTuple,
      MarketStatusUpdatedEvent.OutputTuple,
      MarketStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlementUpdated(address,address)": TypedContractEvent<
      SettlementUpdatedEvent.InputTuple,
      SettlementUpdatedEvent.OutputTuple,
      SettlementUpdatedEvent.OutputObject
    >;
    SettlementUpdated: TypedContractEvent<
      SettlementUpdatedEvent.InputTuple,
      SettlementUpdatedEvent.OutputTuple,
      SettlementUpdatedEvent.OutputObject
    >;

    "VaultUpdated(address,address)": TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
    VaultUpdated: TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
  };
}
