/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchNonce"
      | "emergencyWithdraw"
      | "generateTradeId"
      | "owner"
      | "renounceOwnership"
      | "setSettlementOperator"
      | "settleTrades"
      | "settledTrades"
      | "settlementOperator"
      | "transferOwnership"
      | "vault"
      | "verifySettlement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchSettled"
      | "OwnershipTransferred"
      | "SettlementOperatorUpdated"
      | "TradeSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generateTradeId",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTrades",
    values: [
      BytesLike[],
      AddressLike[],
      AddressLike[],
      AddressLike,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settledTrades",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySettlement",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "batchNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateTradeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settledTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySettlement",
    data: BytesLike
  ): Result;
}

export namespace BatchSettledEvent {
  export type InputTuple = [
    batchNonce: BigNumberish,
    tradeCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchNonce: bigint,
    tradeCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchNonce: bigint;
    tradeCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementOperatorUpdatedEvent {
  export type InputTuple = [oldOperator: AddressLike, newOperator: AddressLike];
  export type OutputTuple = [oldOperator: string, newOperator: string];
  export interface OutputObject {
    oldOperator: string;
    newOperator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeSettledEvent {
  export type InputTuple = [
    tradeId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: string,
    buyer: string,
    seller: string,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tradeId: string;
    buyer: string;
    seller: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Settlement extends BaseContract {
  connect(runner?: ContractRunner | null): Settlement;
  waitForDeployment(): Promise<this>;

  interface: SettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchNonce: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  generateTradeId: TypedContractMethod<
    [
      market: string,
      buyOrderId: string,
      sellOrderId: string,
      sequence: BigNumberish,
      price: BigNumberish,
      quantity: BigNumberish
    ],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setSettlementOperator: TypedContractMethod<
    [_operator: AddressLike],
    [void],
    "nonpayable"
  >;

  settleTrades: TypedContractMethod<
    [
      tradeIds: BytesLike[],
      buyers: AddressLike[],
      sellers: AddressLike[],
      token: AddressLike,
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  settledTrades: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  settlementOperator: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  verifySettlement: TypedContractMethod<
    [tradeId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "generateTradeId"
  ): TypedContractMethod<
    [
      market: string,
      buyOrderId: string,
      sellOrderId: string,
      sequence: BigNumberish,
      price: BigNumberish,
      quantity: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSettlementOperator"
  ): TypedContractMethod<[_operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleTrades"
  ): TypedContractMethod<
    [
      tradeIds: BytesLike[],
      buyers: AddressLike[],
      sellers: AddressLike[],
      token: AddressLike,
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settledTrades"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "settlementOperator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifySettlement"
  ): TypedContractMethod<[tradeId: BytesLike], [boolean], "view">;

  getEvent(
    key: "BatchSettled"
  ): TypedContractEvent<
    BatchSettledEvent.InputTuple,
    BatchSettledEvent.OutputTuple,
    BatchSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlementOperatorUpdated"
  ): TypedContractEvent<
    SettlementOperatorUpdatedEvent.InputTuple,
    SettlementOperatorUpdatedEvent.OutputTuple,
    SettlementOperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeSettled"
  ): TypedContractEvent<
    TradeSettledEvent.InputTuple,
    TradeSettledEvent.OutputTuple,
    TradeSettledEvent.OutputObject
  >;

  filters: {
    "BatchSettled(uint256,uint256,uint256)": TypedContractEvent<
      BatchSettledEvent.InputTuple,
      BatchSettledEvent.OutputTuple,
      BatchSettledEvent.OutputObject
    >;
    BatchSettled: TypedContractEvent<
      BatchSettledEvent.InputTuple,
      BatchSettledEvent.OutputTuple,
      BatchSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlementOperatorUpdated(address,address)": TypedContractEvent<
      SettlementOperatorUpdatedEvent.InputTuple,
      SettlementOperatorUpdatedEvent.OutputTuple,
      SettlementOperatorUpdatedEvent.OutputObject
    >;
    SettlementOperatorUpdated: TypedContractEvent<
      SettlementOperatorUpdatedEvent.InputTuple,
      SettlementOperatorUpdatedEvent.OutputTuple,
      SettlementOperatorUpdatedEvent.OutputObject
    >;

    "TradeSettled(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
    TradeSettled: TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
  };
}
